# Generated by Django 4.2.10 on 2026-05-08 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_rename_content_post_memo_post_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='memo',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
