# Generated by Django 4.2.10 on 2026-05-08 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_alter_post_memo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='memo',
            new_name='content',
        ),
    ]
